changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Added
      labels:
        - feature
        - enhancement
    - title: Changed
      labels:
        - breaking-change
    - title: Fixed
      labels:
        - bug
    - title: Docs
      labels:
        - documentation
        - changelog
    - title: Internal
      labels:
        - infra
        - tests
        - task
    - title: Other Changes
      labels:
        - "*"
